# Default profile, can be used for local development

#spring.profiles.active=local
message: this is default
anothermessage: this is another message from default
# Dev0 profile
---
spring:
  profiles: dev0
message: this is dev0

# Sprint profile
---
spring:
  profiles: sprint
message: this is sprint

# Prod profile
---
spring:
  profiles: prod
message: this is prod
# even if the 'anothermessage' property is not explicitly defined here,
# it is available in the profile from the default profile